lines = [
    'import sys\n',
    'sys.path.append(".")\n',
    'import io, base64\n',
    'import torch\n',
    'from fastapi import FastAPI, File, UploadFile, Form\n',
    'from fastapi.middleware.cors import CORSMiddleware\n',
    'from fastapi.responses import JSONResponse\n',
    'from PIL import Image\n',
    'import numpy as np\n',
    'from pathlib import Path\n',
    'from backend.models.model_loader import load_model, run_inference\n',
    '\n',
    'Path("outputs").mkdir(exist_ok=True)\n',
    'app = FastAPI(title="VeriTrace AI")\n',
    'app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])\n',
    '\n',
    'model = None\n',
    'processor = None\n',
    'device = None\n',
    '\n',
    'def get_model():\n',
    '    global model, processor, device\n',
    '    if model is None:\n',
    '        model, processor, device = load_model()\n',
    '    return model, processor, device\n',
    '\n',
    'def image_to_base64(image):\n',
    '    buffer = io.BytesIO()\n',
    '    image.save(buffer, format="PNG")\n',
    '    buffer.seek(0)\n',
    '    return base64.b64encode(buffer.getvalue()).decode("utf-8")\n',
    '\n',
    'def bytes_to_image(file_bytes):\n',
    '    return Image.open(io.BytesIO(file_bytes)).convert("RGB").resize((224, 224))\n',
    '\n',
    '@app.get("/")\n',
    'def root():\n',
    '    return {"message": "VeriTrace AI running!"}\n',
    '\n',
    '@app.get("/health")\n',
    'def health():\n',
    '    return {"status": "healthy"}\n',
    '\n',
    '@app.post("/analyze")\n',
    'async def analyze(file: UploadFile = File(...), question: str = Form(default="What do you see?")):\n',
    '    try:\n',
    '        m, p, d = get_model()\n',
    '        image = bytes_to_image(await file.read())\n',
    '        answer = run_inference(m, p, d, image, question)\n',
    '        img_b64 = image_to_base64(image)\n',
    '        arr = np.array(image)\n',
    '        gray = arr.mean(axis=2).astype(np.uint8)\n',
    '        heatmap = Image.fromarray(gray)\n',
    '        h_b64 = image_to_base64(heatmap)\n',
    '        return JSONResponse({"success": True, "question": question, "answer": answer, "original_image": img_b64, "heatmap_image": h_b64, "overlay_image": img_b64})\n',
    '    except Exception as e:\n',
    '        return JSONResponse({"success": False, "error": str(e)}, status_code=500)\n',
    '\n',
    '@app.post("/counterfactual")\n',
    'async def counterfactual(file: UploadFile = File(...), question: str = Form(default="What do you see?"), x1: float = Form(default=0.25), y1: float = Form(default=0.25), x2: float = Form(default=0.75), y2: float = Form(default=0.75), mask_type: str = Form(default="black")):\n',
    '    try:\n',
    '        m, p, d = get_model()\n',
    '        image = bytes_to_image(await file.read())\n',
    '        original_answer = run_inference(m, p, d, image, question)\n',
    '        from PIL import ImageDraw\n',
    '        masked = image.copy()\n',
    '        w, h = masked.size\n',
    '        ImageDraw.Draw(masked).rectangle([int(x1*w), int(y1*h), int(x2*w), int(y2*h)], fill=(0,0,0))\n',
    '        masked_answer = run_inference(m, p, d, masked, question)\n',
    '        return JSONResponse({"success": True, "question": question, "original_answer": original_answer, "masked_answer": masked_answer, "answer_changed": original_answer != masked_answer, "original_image": image_to_base64(image), "masked_image": image_to_base64(masked)})\n',
    '    except Exception as e:\n',
    '        return JSONResponse({"success": False, "error": str(e)}, status_code=500)\n',
    '\n',
    '@app.post("/prompt-variations")\n',
    'async def prompt_variations(file: UploadFile = File(...), questions: str = Form(default="What do you see?|Describe this image.")):\n',
    '    try:\n',
    '        m, p, d = get_model()\n',
    '        image = bytes_to_image(await file.read())\n',
    '        results = []\n',
    '        for q in questions.split("|"):\n',
    '            a = run_inference(m, p, d, image, q.strip())\n',
    '            results.append({"question": q.strip(), "answer": a})\n',
    '        return JSONResponse({"success": True, "results": results, "image": image_to_base64(image)})\n',
    '    except Exception as e:\n',
    '        return JSONResponse({"success": False, "error": str(e)}, status_code=500)\n',
    '\n',
    'if __name__ == "__main__":\n',
    '    import uvicorn\n',
    '    uvicorn.run(app, host="0.0.0.0", port=8000)\n',
]
with open("backend/api/main.py", "w") as f:
    f.writelines(lines)
print("Done!")